# Generated by Django 4.0.6 on 2022-07-31 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False, verbose_name='Номер заказа')),
                ('usd_cost', models.DecimalField(decimal_places=0, max_digits=5, verbose_name='Стоимость в долл.США')),
                ('rub_cost', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Стоимость в руб.')),
                ('shipment_date', models.DateField(verbose_name='Дата отгрузки')),
            ],
            options={
                'db_table': 'orders',
            },
        ),
    ]
