# Generated by Django 4.0.6 on 2022-07-31 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='usd_cost',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Стоимость в долл.США'),
        ),
    ]
